{
	"patcher" : {
		"fileversion" : 1,
		"appversion" : { "major" : 8, "minor" : 6, "revision" : 0, "architecture" : "x64" },
		"rect" : [ 60.0, 60.0, 1020.0, 780.0 ],
		"bglocked" : 0, "openinpresentation" : 0,
		"default_fontsize" : 13.0, "default_fontface" : 0, "default_fontname" : "Arial",
		"gridonopen" : 1, "gridsize" : [ 15.0, 15.0 ],
		"boxes" : [

			{ "box" : { "id":"t0", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 12.0, 700.0, 22.0 ],
				"text":"Voice2Piano  Layer 1 Monitor  --  pYIN + onset detection",
				"fontsize":15.0, "fontface":1 } },

			{ "box" : { "id":"t1", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 36.0, 700.0, 18.0 ],
				"text":"SETUP: double-click [notein] below and select port  Voice2Piano_Layer1" } },

			{ "box" : { "id":"sep1", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 58.0, 780.0, 1.0 ], "text":"" } },

			{ "box" : { "id":"obj-notein", "maxclass":"newobj",
				"numinlets":0, "numoutlets":3, "outlettype":["int","int","int"],
				"patching_rect":[ 30.0, 68.0, 260.0, 25.0 ],
				"text":"notein",
				"hint":"STEP 1: double-click here, select Voice2Piano_Layer1 from the list" } },

			{ "box" : { "id":"lbl-notein", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 300.0, 72.0, 500.0, 18.0 ],
				"text":"<-- receives note pitch (outlet 0), velocity (outlet 1), channel (outlet 2)" } },

			{ "box" : { "id":"lbl-kb", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 104.0, 500.0, 18.0 ],
				"text":"KEYBOARD  -- the detected note lights up in real time. note off = key goes dark.",
				"fontface":1 } },

			{ "box" : { "id":"obj-kslider", "maxclass":"kslider",
				"numinlets":2, "numoutlets":2, "outlettype":["int","int"],
				"patching_rect":[ 30.0, 124.0, 760.0, 60.0 ],
				"hint":"inlet 0 = note number (lights up key)  inlet 1 = velocity (0 = note off = dark)" } },

			{ "box" : { "id":"lbl-hist", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 196.0, 760.0, 18.0 ],
				"text":"NOTE HISTORY  -- each bar is one detected note. bar height = pitch (C2 at bottom, C7 at top). scrolls left as new notes arrive.",
				"fontface":1 } },

			{ "box" : { "id":"obj-multislider", "maxclass":"multislider",
				"numinlets":1, "numoutlets":2, "outlettype":["","int"],
				"patching_rect":[ 30.0, 216.0, 760.0, 120.0 ],
				"size":80, "min":36, "max":96, "style":"bar",
				"hint":"receives  prepend append <note>  messages. each append adds a bar on the right and shifts older bars left." } },

			{ "box" : { "id":"obj-prepend", "maxclass":"newobj",
				"numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect":[ 30.0, 358.0, 120.0, 25.0 ],
				"text":"prepend append",
				"hint":"wraps the note number in an 'append' message so multislider adds it as a new rightmost bar" } },

			{ "box" : { "id":"obj-noteongate", "maxclass":"newobj",
				"numinlets":1, "numoutlets":2, "outlettype":["bang","int"],
				"patching_rect":[ 220.0, 358.0, 55.0, 25.0 ],
				"text":"sel 0",
				"hint":"sel 0: bangs when velocity = 0 (note off). used to close the gate so note-offs are not drawn as bars in the history" } },

			{ "box" : { "id":"obj-gate", "maxclass":"newobj",
				"numinlets":2, "numoutlets":2, "outlettype":["int","int"],
				"patching_rect":[ 30.0, 328.0, 65.0, 25.0 ],
				"text":"gate 1",
				"hint":"gate: only passes the note number to prepend when the gate is open (= note on, velocity > 0). closes when note off arrives." } },

			{ "box" : { "id":"lbl-info", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 400.0, 200.0, 18.0 ],
				"text":"LIVE READOUTS", "fontface":1 } },

			{ "box" : { "id":"obj-note-num", "maxclass":"number",
				"numinlets":1, "numoutlets":2, "outlettype":["","bang"],
				"patching_rect":[ 30.0, 420.0, 70.0, 25.0 ],
				"hint":"current MIDI note number (0-127). middle C = 60." } },
			{ "box" : { "id":"lbl-note-num", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 108.0, 424.0, 200.0, 18.0 ], "text":"MIDI note number  (0-127)" } },

			{ "box" : { "id":"obj-vel", "maxclass":"number",
				"numinlets":1, "numoutlets":2, "outlettype":["","bang"],
				"patching_rect":[ 30.0, 454.0, 70.0, 25.0 ],
				"hint":"velocity. Python always sends 80. 0 = note off." } },
			{ "box" : { "id":"lbl-vel", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 108.0, 458.0, 220.0, 18.0 ], "text":"Velocity  (80 = note on,  0 = note off)" } },

			{ "box" : { "id":"obj-mtoname", "maxclass":"newobj",
				"numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect":[ 30.0, 492.0, 80.0, 25.0 ],
				"text":"mtoname",
				"hint":"converts MIDI note number to note name string, e.g. 60 -> C4" } },
			{ "box" : { "id":"obj-notename", "maxclass":"message",
				"numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect":[ 120.0, 492.0, 130.0, 25.0 ],
				"hint":"displays the note name: C4, D#3, G5 etc." } },
			{ "box" : { "id":"lbl-notename", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 260.0, 496.0, 200.0, 18.0 ], "text":"note name (e.g. C4, D#3)" } },

			{ "box" : { "id":"obj-sel0", "maxclass":"newobj",
				"numinlets":1, "numoutlets":2, "outlettype":["bang",""],
				"patching_rect":[ 230.0, 420.0, 55.0, 25.0 ],
				"text":"sel 0",
				"hint":"bangs when velocity = 0 (note off), triggers message 0 to clear kslider" } },
			{ "box" : { "id":"obj-clearmsg", "maxclass":"message",
				"numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect":[ 230.0, 454.0, 50.0, 25.0 ], "text":"0",
				"hint":"sends 0 to kslider inlet 0, which turns off (darkens) the currently lit key" } },

			{ "box" : { "id":"obj-print", "maxclass":"newobj",
				"numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 532.0, 150.0, 25.0 ],
				"text":"print Voice2Piano",
				"hint":"logs every note name to the Max console. open console with Cmd+Shift+C" } },

			{ "box" : { "id":"lbl-mode", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 574.0, 600.0, 18.0 ],
				"text":"ENGINE MODE SWITCH  --  sends MIDI CC14 to Python to change the pitch detection mode at runtime",
				"fontface":1 } },
			{ "box" : { "id":"lbl-mode2", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 594.0, 700.0, 18.0 ],
				"text":"SETUP: double-click [midiout] below and select port  Voice2Piano_ModeSwitch" } },

			{ "box" : { "id":"obj-btn-voice", "maxclass":"button",
				"numinlets":1, "numoutlets":1, "outlettype":["bang"],
				"patching_rect":[ 30.0, 618.0, 24.0, 24.0 ] } },
			{ "box" : { "id":"lbl-voice", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 58.0, 622.0, 160.0, 18.0 ], "text":"Voice only  (pYIN)" } },

			{ "box" : { "id":"obj-btn-instr", "maxclass":"button",
				"numinlets":1, "numoutlets":1, "outlettype":["bang"],
				"patching_rect":[ 200.0, 618.0, 24.0, 24.0 ] } },
			{ "box" : { "id":"lbl-instr", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 228.0, 622.0, 180.0, 18.0 ], "text":"Instrument only  (aubio)" } },

			{ "box" : { "id":"obj-btn-auto", "maxclass":"button",
				"numinlets":1, "numoutlets":1, "outlettype":["bang"],
				"patching_rect":[ 400.0, 618.0, 24.0, 24.0 ] } },
			{ "box" : { "id":"lbl-auto", "maxclass":"comment", "numinlets":1, "numoutlets":0,
				"patching_rect":[ 428.0, 622.0, 160.0, 18.0 ], "text":"Auto  (default)" } },

			{ "box" : { "id":"obj-msg-voice", "maxclass":"message",
				"numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect":[ 30.0, 656.0, 120.0, 25.0 ], "text":"176 14 0" } },
			{ "box" : { "id":"obj-msg-instr", "maxclass":"message",
				"numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect":[ 200.0, 656.0, 120.0, 25.0 ], "text":"176 14 1" } },
			{ "box" : { "id":"obj-msg-auto", "maxclass":"message",
				"numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect":[ 400.0, 656.0, 120.0, 25.0 ], "text":"176 14 2" } },

			{ "box" : { "id":"obj-midiout", "maxclass":"newobj",
				"numinlets":1, "numoutlets":0,
				"patching_rect":[ 30.0, 698.0, 260.0, 25.0 ],
				"text":"midiout",
				"hint":"STEP 2: double-click here, select Voice2Piano_ModeSwitch from the list" } }
		],
		"lines" : [
			{ "patchline" : { "source":["obj-notein",0], "destination":["obj-kslider",0] } },
			{ "patchline" : { "source":["obj-notein",0], "destination":["obj-note-num",0] } },
			{ "patchline" : { "source":["obj-notein",0], "destination":["obj-mtoname",0] } },
			{ "patchline" : { "source":["obj-notein",0], "destination":["obj-gate",0] } },
			{ "patchline" : { "source":["obj-notein",1], "destination":["obj-vel",0] } },
			{ "patchline" : { "source":["obj-notein",1], "destination":["obj-sel0",0] } },
			{ "patchline" : { "source":["obj-notein",1], "destination":["obj-noteongate",0] } },
			{ "patchline" : { "source":["obj-noteongate",1], "destination":["obj-gate",1] } },
			{ "patchline" : { "source":["obj-gate",0], "destination":["obj-prepend",0] } },
			{ "patchline" : { "source":["obj-prepend",0], "destination":["obj-multislider",0] } },
			{ "patchline" : { "source":["obj-sel0",0], "destination":["obj-clearmsg",0] } },
			{ "patchline" : { "source":["obj-clearmsg",0], "destination":["obj-kslider",0] } },
			{ "patchline" : { "source":["obj-mtoname",0], "destination":["obj-notename",0] } },
			{ "patchline" : { "source":["obj-mtoname",0], "destination":["obj-print",0] } },
			{ "patchline" : { "source":["obj-btn-voice",0], "destination":["obj-msg-voice",0] } },
			{ "patchline" : { "source":["obj-btn-instr",0], "destination":["obj-msg-instr",0] } },
			{ "patchline" : { "source":["obj-btn-auto",0], "destination":["obj-msg-auto",0] } },
			{ "patchline" : { "source":["obj-msg-voice",0], "destination":["obj-midiout",0] } },
			{ "patchline" : { "source":["obj-msg-instr",0], "destination":["obj-midiout",0] } },
			{ "patchline" : { "source":["obj-msg-auto",0], "destination":["obj-midiout",0] } }
		]
	}
}
